### ISSUE TITLE
seg faults w/ docking and undocking mutations window

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bitsed/qosmic#1]
```
I recently dl'ed qosmic and received a segmentation fault when undocking
and redocking the mutations window after applying a variation. I ran qosmic
in valgrind and fixed a few memory mismatches which, so far, seems to have
solved the seg faults. (version 1.4.2, debian amd-64)

Patch included.

Thanks,
-jill
```

Original issue reported on code.google.com by `jill.ump...@gmail.com` on 21 Dec 2008 at 8:48

Attachments:
* [qosmic-valgrind.patch](https://storage.googleapis.com/google-code-attachments/qosmic/issue-1/comment-0/qosmic-valgrind.patch)

**Comment by bitsed** [comment]
Problem has not been seen recently.  Please reopen if this reappears.
