### ISSUE TITLE
Add qosmic.desktop

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bitsed/qosmic#22]
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Qosmic
GenericName=Flam3 Fractal Editor
GenericName[ru]=Редактор фракталов Flam3
Comment=A cosmic recursive flame fractal editor written in Qt
Comment[ru]=Рекурсивный фрактальный редактор
Exec=qosmic
Icon=/usr/share/pixmaps/qosmicicon.xpm
Terminal=false
Categories=Qt;KDE;Graphics;
```

Original issue reported on code.google.com by `loginov.alex.valer@gmail.com` on 5 Oct 2014 at 12:52

**Comment by bitsed** [comment]
I added the qosmic.desktop file posted in the comment.  I'm not sure if the value for the "Icon" field is correct.  What is an appropriate value for this field?

**Comment by bitsed** [comment]
The qosmic.desktop file has been added.
Thanks!
