### ISSUE TITLE
Unreadable text on the "Variations" panel

### ISSUE THREAD

**Issue by denilsonsa** [bitsed/qosmic#45]
When running Qosmic while having a dark desktop theme, the "Variations" panel will have white text on top of white background:

![Qosmic screenshot](https://github.com/bitsed/qosmic/assets/121676/537c291b-17d2-4ba6-9816-e3a592f03829)

The "Chaos" panel seems to use a similar widget, and it is perfectly readable:

![Qosmic screenshot - Chaos panel](https://github.com/bitsed/qosmic/assets/121676/471ef2f6-f427-4fd6-80af-002545fd8c0b)

## System information

* Manjaro Linux x86_64
* KDE/Plasma with *Breeze Dark* theme
* Qosmic 1.6.0 compiled from source using [AUR](https://aur.archlinux.org/packages/qosmic)

**Comment by denilsonsa** [comment]
I've prepared a quick patch that solves the issue:

![Screenshot of the Variations panel following the user's theme](https://github.com/bitsed/qosmic/assets/121676/ce706e67-110c-49f2-a3d9-0cd2fad4d46e)

I'm sending a pull request.

**Comment by bitsed** [comment]
Hi.  Thank you for the bug report and the patch in #46.  It's been merged with the master branch.

I've created an alternative patch that may solve your problem and keep the highlighted text behavior.  It can be found at the head of the issues-46 branch.  https://github.com/bitsed/qosmic/compare/issues-46

I'm not easily able to test it right now.  I don't have KDE/Plasma or dark themes installed.  I'd appreciate your help if you're able to build and test issues-46.  Thanks!

**Comment by denilsonsa** [comment]
Seems to be working fine:

![image](https://github.com/bitsed/qosmic/assets/121676/e7d7f788-bc00-4448-aea1-e27189298818)

I could complain that it is now hard to see which item currently has focus, because the focus color is the same as the background color of modified items. Maybe just setting them as bold would be good enough?

Also, maybe slightly increasing the column width as well.

Beyond this quick feedback, your patch seems to work well enough, thank you!
